---
title: "Meteorites Weekend Homework"
subtitle: "Analysis"
output: html_notebook
date: "`r format(Sys.Date())`"
author: "Lesley Duff"
---
# Meteorites Analysis

We have data from [NASA](https://www.nasa.gov/) which has information on 
meteorites that have been found up to the year 2013.

```{r}
source("cleaning.R")

# Read the cleaned data into R.
meteorite_data <- process_meteorite_landings_file("data/meteorite_landings.csv")
```
## Names and years for the 10 largest meteorites

```{r}
# Find the names and years found for the 10 largest meteorites in the data.
meteorite_data %>% 
  slice_max(mass_g, n = 10) %>% 
  select(name, year)
```
## Average mass of meteorites

```{r}
# Find the average mass of meteorites that were recorded falling, vs. those 
# which were just found.
meteorite_data %>% 
  group_by(fall) %>% 
  summarise(avg_mass_g = mean(mass_g, na.rm = TRUE))
```

## Number of meteorites in each year, for every year since 2000.

```{r}
# Find the number of meteorites in each year, for every year since 2000.
meteorite_data %>% 
  filter(year >= 2000) %>% 
  group_by(year) %>% 
  summarise(number_of_meteorites = n())
```

## Function get_meteorite_count()

```{r}
#Write a function called get_meteorite_count() that takes in two arguments: 
#  a dataframe and a year, and returns the phrase "In (input_year), there were 
#(number of meteorites that year) meteorites." IF there are 1 or more meteorites 
#that year. If there are no meteorites in the year, return the phrase "As far as 
#we know, there were no meteorites that year".
get_meteorite_count <- function(dataframe, input_year){
  output <- ""

  number_of_meteorites <- 2
#  number_of_meteorites <- 0
  
  if (number_of_meteorites >= 1) {
    output <- str_c("In ", input_year, ", there were ", number_of_meteorites, 
                    " meteorites.")
  } else {
    output <- "As far as we know, there were no meteorites that year"
  }
    
 return (output)
#  In (input_year), there were (number of meteorites that year) meteorites.
#  As far as we know, there were no meteorites that year
}

count_meteorite <- get_meteorite_count(meteorite_data, 2009)
print(count_meteorite)
```

